s = input('Digite algo: ')
print('O tipo primitivo é ', type(s))
print('É alfabetico? ', s.isalpha())
print('É alfanúmerico? ', s.isalnum())
print('Contém digito decimal? ', s.isdigit())
print('Todos tem letra maiúsculas? ', s.isupper())
print('Está em menúscula? ', s.islower())
print('Tem espaços entre eles? ', s.isspace())
print('É número? ', s.isnumeric())